#!/usr/local/bin/node

/**
* @file average_scores.js
* @brief Add the score averages to the JSON file.
* @author Anadian
* @copyright MITlicensetm(2018,Canosw)
*/

//Dependencies
	//Internal
	//Standard
	//External

//Constants
const FILENAME = 'average_scores.js';
const MODULE_NAME = 'AverageScores';
var PROCESS_NAME = '';
if(require.main === module){
	PROCESS_NAME = 'average_scores';
} else{
	PROCESS_NAME = process.argv0;
}

//Functions

//Exports and Execution
if(require.main === module){
	
} else{
	
}
